const deliveryTypes = {
  FETCH_DELIVERIES_START: 'FETCH_DELIVERIES_START',
  FETCH_DELIVERIES_SUCCESS: 'FETCH_DELIVERIES_SUCCESS',
  FETCH_DELIVERIES_FAILURE: 'FETCH_DELIVERIES_FAILURE',
};

export default deliveryTypes